# Generated by Django 3.0.4 on 2020-03-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='vietnamese_name',
            field=models.CharField(max_length=100),
        ),
    ]
