# Generated by Django 3.0.4 on 2020-03-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20200309_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iupac_name', models.CharField(max_length=400)),
                ('synonym', models.CharField(max_length=100)),
            ],
        ),
    ]
