# Generated by Django 3.0.4 on 2020-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_compound'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='scientific_name',
            field=models.ManyToManyField(to='coreapp.herb'),
        ),
    ]
