# Generated by Django 3.0.4 on 2020-03-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_compound_scientific_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='scientific_name',
        ),
        migrations.AddField(
            model_name='compound',
            name='herb',
            field=models.ManyToManyField(to='coreapp.Herb'),
        ),
    ]
