# Generated by Django 3.0.4 on 2020-03-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_auto_20200310_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='familia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='herb',
            name='vietnamese_synonyms',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='herb',
            name='scientific_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='herb',
            name='vietnamese_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
