# Generated by Django 3.0.4 on 2020-03-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_auto_20200311_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
