# Generated by Django 3.0.4 on 2020-03-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_auto_20200311_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='formula',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='pubchem_ref',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='structure',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
