# Generated by Django 3.0.4 on 2020-03-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_auto_20200312_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='herb',
            field=models.ManyToManyField(related_name='herb', to='coreapp.Herb'),
        ),
    ]
