# Generated by Django 3.0.4 on 2020-03-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_auto_20200312_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_name', models.CharField(max_length=100)),
                ('gene_name', models.CharField(max_length=100)),
                ('compound', models.ManyToManyField(related_name='compound', to='coreapp.Compound')),
                ('herb', models.ManyToManyField(related_name='herb1', to='coreapp.Herb')),
            ],
        ),
    ]
