# Generated by Django 3.0.4 on 2020-03-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_auto_20200312_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='herb',
            field=models.ManyToManyField(related_name='abc', to='coreapp.Herb'),
        ),
        migrations.AlterField(
            model_name='target',
            name='compound',
            field=models.ManyToManyField(related_name='compound', to='coreapp.Compound'),
        ),
    ]
