# Generated by Django 3.0.4 on 2020-03-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_auto_20200312_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='compound',
        ),
    ]
