# Generated by Django 3.0.4 on 2020-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_remove_target_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='herb',
            field=models.ManyToManyField(to='coreapp.Herb'),
        ),
    ]
