# Generated by Django 3.0.4 on 2020-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0019_auto_20200313_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='herb',
            field=models.ManyToManyField(related_name='abc', to='coreapp.Herb'),
        ),
    ]
