# Generated by Django 3.0.4 on 2020-03-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0020_auto_20200313_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='herb',
            field=models.ManyToManyField(related_name='herb', to='coreapp.Herb'),
        ),
    ]
