# Generated by Django 3.0.4 on 2020-03-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0022_auto_20200313_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='herb',
            field=models.ManyToManyField(to='coreapp.Herb'),
        ),
        migrations.AddField(
            model_name='target',
            name='uniprot_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
