# Generated by Django 3.0.4 on 2020-03-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0023_auto_20200313_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='compound',
            field=models.ManyToManyField(to='coreapp.Compound'),
        ),
    ]
