# Generated by Django 3.0.4 on 2020-03-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0024_target_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='synonym',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='compound',
            field=models.ManyToManyField(to='coreapp.Compound'),
        ),
        migrations.AlterField(
            model_name='target',
            name='gene_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='protein_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
