# Generated by Django 3.0.4 on 2020-03-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0031_auto_20200318_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='synonym',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='compound',
            field=models.ManyToManyField(to='coreapp.Compound'),
        ),
    ]
