# Generated by Django 3.0.4 on 2020-03-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0033_auto_20200318_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name_en', models.CharField(max_length=100, unique=True)),
                ('icd10_ref_en', models.CharField(max_length=200)),
                ('icd10_code_en', models.CharField(max_length=50)),
                ('disease_name_vn', models.CharField(max_length=100)),
                ('icd10_ref_vn', models.CharField(max_length=200)),
                ('icd10_code_vn', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='compound',
            field=models.ManyToManyField(to='coreapp.Compound'),
        ),
    ]
