# Generated by Django 3.0.5 on 2020-04-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0034_auto_20200318_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='molcular_wt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='compound',
            field=models.ManyToManyField(to='coreapp.Compound'),
        ),
    ]
