# Generated by Django 3.0.5 on 2020-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0035_auto_20200414_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='molcular_wt',
        ),
        migrations.AddField(
            model_name='compound',
            name='smiles',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='compound',
            field=models.ManyToManyField(to='coreapp.Compound'),
        ),
    ]
