# Generated by Django 3.0.5 on 2020-04-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0037_auto_20200414_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='can_smiles',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='iso_smiles',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='compound',
            field=models.ManyToManyField(to='coreapp.Compound'),
        ),
    ]
